In [2]:
import pandas as pd
import numpy as np
import datetime as dt
import gc
import qgrid
import xgboost

In [7]:
dt.datetime.now().strftime('%H%Mhrs_%d%b%Y')

'0048hrs_26Aug2015'

In [10]:
a = np.arange(5)
print(a)
np.power(a,1/3.)

[0 1 2 3 4]


array([ 0.        ,  1.        ,  1.25992105,  1.44224957,  1.58740105])

In [1]:
qgrid.nbinstall()  # copies javascript dependencies to your /nbextensions folder 

NameError: name 'qgrid' is not defined

In [3]:
an = np.array(range(5))

In [4]:
an

array([0, 1, 2, 3, 4])

In [6]:
pd.DataFrame({"a":an,})

a
0  0
1  1
2  2
3  3
4  4

In [15]:
a = pd.DataFrame({'testCol':['a','b','c'],'val1':[3,3,3],'qty1':[1,0,2],'val2':[2,2,2],'qty2':[np.nan,4,1],
                 'binary':['No','Yes','Yes'],'binary2':['No','Yes','No'],'date':['02122011', '02122014', '31032011']})

In [16]:
qgrid.show_grid(a, remote_js=True)

In [8]:
rdf = pd.DataFrame(data = np.random.rand(73),index=pd.date_range('1 aug 2015','4 aug 2015',freq='H'),columns=['predicted'])

In [17]:
rdf['hour'] = rdf.index.hour
rdf['isweekend'] = rdf.index.weekday > 5

rdf['Date'] = rdf.index.format(formatter=lambda x: pd.to_datetime(x.strftime('%d %b %Y')))
qgrid.show_grid(pd.pivot_table(rdf.loc[~rdf.isweekend],values='predicted',columns='hour',index='Date'), remote_js=True)


In [18]:
qgrid.show_grid(rdf, remote_js=False)

In [11]:
del a
gc.collect()
qgrid.show_grid(acopy, remote_js=True)
#acopy

NameError: name 'acopy' is not defined

In [5]:
a.date = a.date.apply(lambda x: pd.to_datetime(x, format = "%d%m%Y"))

NameError: name 'a' is not defined

In [12]:
a.rename_axis({'val1':'val2'},axis=1,inplace=True)
a

NameError: name 'a' is not defined

In [13]:
a['binary2'] = ['Yes','Yes','No']
#a.rename_axis({'binary2':'binary'},axis=1,inplace=True)
a

NameError: name 'a' is not defined

In [14]:
tp = pd.get_dummies(a[['binary','binary2']].stack())#.sum(level=1)

NameError: name 'a' is not defined

In [ ]:
pd.get_dummies(a[['binary','binary2']].stack()).sum(level=0)

In [51]:
pd.get_dummies(a[['binary']].stack()).sum(level=0)

No  Yes
0   1    0
1   0    1

In [58]:
type(a[['binary','binary']])

pandas.core.frame.DataFrame

In [4]:
a.rename_axis({'binary':'magic', 'binary2':'magic', 0:'zero'},inplace=True,axis=1)
a

magic  qty1  qty2 testCol  val1  val2 magic
0    No     1   NaN       a     3     2    No
1   Yes     0     4       b     3     2   Yes
2   NaN     2     1       c     3     2   NaN

In [15]:
b = pd.get_dummies(a['magic'].stack()).reset_index(level=1)
b.groupby(b.index).sum()

No  Yes
0   2    0
1   0    2

In [9]:
a['t1'],a['t2'] = a.val1.apply(lambda x: x+1,x+2)
a

NameError: name 'x' is not defined

In [6]:
a.qty1 += a.val1
a

binary  qty1  qty2 testCol  val1  val2
0     No     4   NaN       a     3     2
1    Yes     3     4       b     3     2
2    NaN     5     1       c     3     2

In [29]:
a['binary'] = a['binary'].apply(lambda x: x if str(x) in 'Yes' else np.nan)
a

binary  qty1  qty2 testCol  val1  val2
0    NaN     1   NaN       a     3     2
1    Yes     0     4       b     3     2
2    NaN     2     1       c     3     2

In [30]:
a_dummies = pd.get_dummies(a.binary)
a[['binary_'+col for col in a_dummies.columns]] = a_dummies 

In [16]:
def add_dummies(df,colname):
    col_dummies = pd.get_dummies(df[colname])
    df[[colname+'_'+ col for col in col_dummies.columns]] = col_dummies

In [31]:
add_dummies(a,'binary')
a

binary  qty1  qty2 testCol  val1  val2  binary_Yes
0    NaN     1   NaN       a     3     2           0
1    Yes     0     4       b     3     2           1
2    NaN     2     1       c     3     2           0

In [38]:
a.loc[a.binary == 'Yes','binary'] = 1
a.loc[a.binary <> 1,'binary'] = 0
a

binary  qty1  qty2 testCol  val1  val2
0      0     1   NaN       a     3     2
1      1     0     4       b     3     2
2      0     2     1       c     3     2

In [25]:
a['sumproduct'] = sum([a['qty'+str(i)].fillna(0)*a['val'+str(i)] for i in range(1,3)])

In [29]:
b 

qty1  qty2 testCol  val1  val2  sumproduct  test
0     1   NaN       a     3     2           3   NaN
1     0     4       b     3     2           8   NaN
2     2     1       c     3     2           8   NaN

qty1  qty2 testCol  val1  val2  sumproduct      test
0     1     0       a     3     2           3       inf
1     0     4       b     3     2           8  0.000000
2     2     1       c     3     2           8       inf

In [13]:
a= ['asdf','asdf']
a.append('test')

In [14]:
a

['asdf', 'asdf', 'test']

In [3]:
b = pd.DataFrame({'testCol':[1,2,3],'val1':[3,3,3],'qty1':[1,0,2],'val2':[2,2,2],'qty2':[np.nan,4,1],
                 'binary':['No','Yes',np.nan],'date':['02122011', '02122014', '31032011']})

In [4]:
b

binary      date  qty1  qty2  testCol  val1  val2
0     No  02122011     1   NaN        1     3     2
1    Yes  02122014     0     4        2     3     2
2    NaN  31032011     2     1        3     3     2

In [6]:
b.qty1.replace({1:'NANANA'})

0    NANANA
1         0
2         2
Name: qty1, dtype: object

In [74]:
print(b.agg([np.max,np.min,np.mean,np.sum]))
#print(b.iloc[:,2:].sum(axis=1))
#print(b.iloc[:,2:].min(axis=1))
#print(b.iloc[:,2:].mean(axis=1))

AttributeError: 'DataFrame' object has no attribute 'agg'

In [66]:
b[['val1','val2']] * b.sum()[['val1','val2']]

val1  val2
0    27    12
1    27    12
2    27    12

In [78]:
alist = []
alist.extend('test_alist')
alist

['t', 'e', 's', 't', '_', 'a', 'l', 'i', 's', 't']